from node:8.16.1-alpine

ARG APP_DIR=/var/www
RUN mkdir -p ${APP_DIR}
WORKDIR ${APP_DIR}/assets/frontend

COPY ./docker-entrypoint.sh /
RUN chmod +x /docker-entrypoint.sh
ENTRYPOINT ["/docker-entrypoint.sh"]
